#ifndef H_GAME_OF_LIFE_CONSTANTS
#define H_GAME_OF_LIFE_CONSTANTS

#define W_COLS 500
#define W_ROWS 500
#define CELL_SIZE 10
#define FLAT_ENVIRONMENT_LENGTH W_ROWS * W_COLS 
#define COLOR_BLACK 0x000000
#define COLOR_GRAY_DARK 0x080808
#define COLOR_WHITE 0xFFFFFF
#define COLOR_RED 0xFF0000
#define COLOR_GREEN 0x00FF00
#define COLOR_BLUE 0x0000FF
#define RULE_DEAD_TO_ALIVE_REQUIRES_ALIVE 3
#define RULE_STAYING_ALIVE_EXPECTS_MIN_ALIVE 2
#define RULE_STAYING_ALIVE_EXPECTS_MAX_ALIVE 3

#endif
